spring.application.name=clinic_api

spring.datasource.url=jdbc:mysql://switchback.proxy.rlwy.net:18257/railway
spring.datasource.username=root
spring.datasource.password=vpUbExWmukvEapDqDnGMqqEzmIMIRDXO

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

server.port=8080